services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=keystone_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio:latest
    command: server --console-address ":9001" /data
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - "9000"
      - "9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - minio_volume:/data
  k3yst0n3:
    hostname: k3yst0n3
    build: .
    depends_on:
      - postgres
      - minio
    ports:
      - 4000:4000

volumes:
  postgres_volume:
  minio_volume:

