services:
  minio:
    hostname: minio
    image: quay.io/minio/minio:latest
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - "9000"
      - "9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data-1:/data
  k3yst0n3:
    hostname: k3yst0n3
    build: .
    depends_on:
      - minio
    ports:
      - 4000:4000

volumes:
  data-1:

