services:
  server:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    command: air ./cmd/main.go -b 0.0.0.0
  minio:
    image: quay.io/minio/minio:latest
    command: server --console-address ":9001" /data
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - "9000"
      - "9001"
    volumes:
      - minio-volume:/data
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  minio-volume:
  postgres-volume:
